language: node_js
cache:
  directories: node_modules
node_js: 8
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: R/wtQnVHwTszImU5ST58AKY0M20gBUZuMGJouQ+9xzx899DYBYWRrhepeHQyPI8mqK9i85v4XYeCVsmfUMFTGc0vhzb+UKc33ffgEBwO8gF4o/sgQp55VKHVgML9FPgE78qH3eJq3i9gi8etdAXAwKJusM95KGiz3wu/tjyd3TxYSRIiErT26Us448kfqhhJmka2mnJ2pqEIG+am6I5FIm5ibme3lAnCnrATOIeak8cZ5I/7Rmk83zk8vmTDNH9Ts/cxiNLUkcPbJiBQUpld35Mj4iqvD7ye/POrqFcMHYCgAVZbCw/8MvgbxPCTgfFJzChEmNyxkE+qVzBnXk1qRe5gOtZwEwy3e9WCZXajOoZuLKXwpnaK6eoxID/xY+yvLVIGpX/yUaKgUXtOZdP7Tc/38gCjTqPj+p35Wt+yJuNAycwTWyHnaVlULIuzuGOoLzlii2O/lk25zAeMMZWnscp1JteJoo39Mn1X7rqgL0udyELwHMFaXN4atz2cZxknOInzNpKTzR+HWXJ0hrwxF7mncCARcv2Fo/GFPmJ4h4zNdQq0ijLTwptEPKcVc9xcn5MVK3ZPjU8TX3Ps35TbNTA0C1yzeDg0g4W4+jKjXc6SzW0lvAkT2qy8VGIV9fy2Eyovd+/pgTYVlZFJPLlVPPN65O4YJoL8DcrT9Hyh4g0=
